//! IMPORTS
//* dependencies
import { useState, ChangeEvent } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import ParentSize from '@visx/responsive/lib/components/ParentSize';

//* utils
import { marketCapData } from '@/data/index';

//* components
import LineChart from '@/components/Charts/LineChart';
import MicrosoftStats from '@/components/Dashboard/MicrosoftStats';
import Loading from '@/components/Shared/Loading';

//* constants
const companies = marketCapData.map((elm) => elm.company);
const companiesNames = [...new Set(companies)];

//! JSX
const HomePage: NextPage = () => {
  const [checked, setChecked] = useState<Array<string>>(companiesNames);

  // Add / Remove checked item from list
  const handleCheck = (e: ChangeEvent<HTMLInputElement>) => {
    let updatedList = [...checked];
    if (e.target.checked) {
      updatedList = [...checked, e.target.value];
    } else {
      updatedList.splice(checked.indexOf(e.target.value), 1);
    }
    setChecked(updatedList);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-5xl font-bold uppercase">Market Cap</h1>
        <ul className="mt-12 flex space-x-6">
          {companiesNames.map((company, idx) => (
            <div key={idx} className="space-x-2">
              <label>{company}</label>
              <input
                type="checkbox"
                value={company}
                id={company}
                defaultChecked
                onChange={handleCheck}
              />
            </div>
          ))}
        </ul>

        <div className="p-8">
          <h3 className="text-lg font-medium leading-6 text-gray-900">
            Dashboard
          </h3>

          <div className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3">
            <MicrosoftStats />
          </div>
        </div>

        <div className="mx-auto h-[576px] w-[720px]">
          <ParentSize>
            {({ width, height }) => (
              <LineChart
                data={marketCapData.filter((elm) =>
                  checked.includes(elm.company)
                )}
                width={width}
                height={height}
              />
            )}
          </ParentSize>
        </div>
      </main>
    </div>
  );
};

export default HomePage;
